- branchNamePattern: '(feature|bugfix)/.*'
  environment: 'PREDEV'
- branchNamePattern: '(develop|hotfix/.*)'
  environment: 'DEV'
# - branchNamePattern: 'cicd-setup'
#   environment: 'DEV'
- branchNamePattern: 'release'
  environment: 'QA'
- branchNamePattern: 'master'
  environment: 'PROD'
